### PR TITLE
￼Added unofficial SDK for etcfv2 implemented in C

### PR DESCRIPTION
**Pull request by guillaumef**
￼Added unofficial SDK for etcfv2 implemented in C

### CODE REVIEW

**Comment by alextcone** [comment]
@guillaumef - do you have a plan for reviewers?

**Comment by guillaumef** [comment]
> @guillaumef - do you have a plan for reviewers?

I don't understand. We are currently using our C implementation in production.
We could add a unit testing if necessary.

**Comment by alextcone** [comment]
@guillaumef - for Tech Lab to add this implementation to this repo we will need a few others who can walk through the code to make sure it is interpreting the overall specification correctly.

**Comment by guillaumef** [comment]
@alextcone - IAB has an old repository, empty, which aimed to provide something similar (https://github.com/InteractiveAdvertisingBureau/Consent-String-SDK-C), perhaps the author of this repository, @jenniferIAB, could "walk through the code", or you can close the pull request if you don't have enough warranty on this opensource contribution, no problem.

**Review by a2intl — APPROVED** [review]
The code seems like a functional, bare-bones, core-segment-only parsing of the TCFv2 string. It does have some basic tests, so I think we can include it in a "Unofficial, not supported, SDK" list.

**Pull request merged**
