### PR TITLE
Add TCData validity condition for client side calls

### PR DESCRIPTION
**Pull request by Leedehai**
Suggest how to check TCData for validity. Here validity means the
TC String is considered a true reflection of user's intention of
consent, or lack thereof.

### CODE REVIEW

**Comment by katiestroudpro** [comment]
Reviewed and updated.

**Comment by Leedehai** [comment]
Hi @katiestroudpro it looks the implementation guideline doc is updated by adding text directly instead of by merging this PR. So does it mean we can close this PR now?

**Comment by katiestroudpro** [comment]
Yes, we can close.

**Comment by Leedehai** [comment]
Hi, it turns out the update in the PR is not merged. Re-opening this.

**Pull request merged**
