### PR TITLE
draft language to clarify restriction to flexibility mismatches

### PR DESCRIPTION
**Pull request by alextcone**

### CODE REVIEW

**Comment by chrispaterson** [comment]
@alextcone I think you should add a line to the change log, so people have a reference to when that was written.

**Comment by alextcone** [comment]
Agree, Chris. Do you approve though? Making this change after the lack of clarity was raised by Xiaoyong.

**Comment by chrispaterson** [comment]
Definitely approved!  I assigned myself as a reviewer and then reviewed the changes and clicked approved to make it official – kind of like a double-spit-shake pinky promise.

**Comment by alextcone** [comment]
Language to clarify RestrictionType cases

**Comment by alextcone** [comment]
Correcting accidental closure

**Pull request merged**
