### PR TITLE
initial special purposes only vendors commit

### PR DESCRIPTION
**Pull request by alextcone**
Handling transparency for vendors who are only signed up for Special Purposes

### CODE REVIEW

**Comment by anderagakura** [comment]
@alextcone After have discussed internally below is the description we would like to push : 

`Vendors that register for Special Purposes only, and no other Purposes, and have been displayed by the CMP, then the value must be set to <code>1</code>. 
Note: Special Purposes are displayed for transparency only and do not enable user choice. `

**Comment by a2intl** [comment]
The "then the value must be set" is incorrect grammar, it should be "should have their value set".

**Comment by anderagakura** [comment]
> The "then the value must be set" is incorrect grammar, it should be "should have their value set".

@a2intl We use "must" because we want to indicate this case is **required** for the vendor’s bit in order to display it for transparency.

**Comment by alextcone** [comment]
Fixed grammar (for @a2intl) while keeping "must" per @anderagakura's last comment. Ready to merge.

**Pull request merged**
